#!/bin/sh
# Copy command-line tool resources out of .app bundle
CMD_TOOL_DIR=/usr/local/bin
CMD_MAN_DIR=/usr/local/share/man/man1
HELPER_BIN_SRC_DIR=/Applications/BBEdit.app/Contents/Helpers
HELPER_MAN_SRC_DIR=/Applications/BBEdit.app/Contents/Resources
LN=/bin/ln

# create dirs if they don't already exist
for DIR in "$CMD_TOOL_DIR" "$CMD_MAN_DIR"; do
    [ -d "$DIR" ] || mkdir -p -m 775 "$DIR"
done
# make symlinks to binaries and manpages
for TOOL in bbdiff bbfind; do
    "$LN" -sf "$HELPER_BIN_SRC_DIR/$TOOL" "$CMD_TOOL_DIR/$TOOL"
    "$LN" -sf "$HELPER_MAN_SRC_DIR/$TOOL.1" "$CMD_MAN_DIR/$TOOL.1"
done
"$LN" -sf "$HELPER_BIN_SRC_DIR/bbedit_tool" "$CMD_TOOL_DIR/bbedit"
"$LN" -sf "$HELPER_MAN_SRC_DIR/bbedit.1" "$CMD_MAN_DIR/bbedit.1"
