#!/bin/bash
# replacement preinstall script for Adobe Acrobat Reader DC

installation_path=$2
readerApp="Adobe Acrobat Reader DC.app"

if [ -e "$installation_path/$readerApp" ] ; then
  /bin/rm -r "$installation_path/$readerApp"
fi
